protected/controllers/CheckoutController.php
<?php

class CheckoutController extends BaseController {

    public $url;
    public $position;
    public $data;

    public function ActionCart() {
        $app = Yii::app();
        $json = array();

        $productDetails = isset($_POST['product_id']) ? $app->product->getProduct((int) $_POST['product_id']) : 0;
        if ($productDetails) {
            $quantity = isset($_POST['quantity']) ? (int) $_POST['quantity'] : 0;

            $option = isset($_POST['option']) ? $_POST['option'] : array();

            $productOptions = $app->product->getProductOptions($productDetails['product_id']);
            foreach ($productOptions as $productOption) {
                if ($productOption['required'] && empty($option[$productOption['id_product_option']])) {
                    $json['error']['option'][$productOption['id_product_option']] = $productOption['name'] . " Required";
                }
            }


            if (!$json) {
                $app->cart->addProduct($productDetails['product_id'], $quantity, $option);
                $json['success'] = Yii::t('checkout', 'text_add_to_cart_success');
                if (Yii::app()->config->getData('CONFIG_WEBSITE_ADDTOCART_REDIRECT')) {
                    //$json['redirect'] = $this->createUrl('product/productdetails', array('product_id' => $productDetails['product_id']));
                    $json['redirect'] = $this->createUrl('checkout/carts');
                }
                $json['total_price']=Yii::app()->currency->format(Yii::app()->cart->getSubTotal());
                $json['total_qty']=Yii::app()->cart->countProducts();
            }
        }
        //echo '<pre>';print_r($json);exit;
        echo json_encode($json);
    }

    public function actionLogin() {
        $app = Yii::app();
        $json = array();
        if ((!$app->cart->hasProducts()) || (!$app->cart->hasStock() && !$app->config->getData('CONFIG_STORE_ALLOW_CHECKOUT'))) {
            $this->redirect($this->createUrl('checkout/carts'));
        }
        $model = new LoginForm;
        if ($_SERVER['REQUEST_METHOD'] == 'POST') {
            if (isset($_POST['acountType'])) {
                $_SESSION['acountType'] = $_POST['acountType'];
            }

            if (isset($_POST['email']) && strtoupper($_SERVER['REQUEST_METHOD']) == 'POST') {
                $model->username = $_POST['email'];
                $model->password = $_POST['password'];
                // validate user input and redirect to the previous page if valid
                if ($model->validate() && $model->login()) {
                    /* $addwishlist = Customer::model()->findByPk(Yii::app()->session['user_id']);
                      $addwishlist->wishlist = serialize(Yii::app()->session['user_whishlist']);
                      $addwishlist->cart = serialize($_SESSION['products']);
                      $addwishlist->update(array('wishlist', 'cart')); */
                } else {
                    $json['error']['warning'] = Yii::t('account', 'text_incorrect_username_password'); // $_SESSION['OBJ']['tr']->translate('error_login_checkout_checkout');
                }
            }
            /* if (isset($_POST['email']) && isset($_POST['password'])) {
              $customer=new Customer;
              if ($customer->login(array('email'=>$_POST['email'],'password'=> $_POST['password']))) {
              unset($_SESSION['guest']);
              } else {
              $json['error']['warning'] =Yii::t('account','text_incorrect_username_password');// $_SESSION['OBJ']['tr']->translate('error_login_checkout_checkout');
              }
              } */
        } else {

            $data['guestCheckout'] = ($app->config->getData('CONFIG_STORE_ALLOW_GUEST_CHECKOUT') && !$app->config->getData('CONFIG_STORE_LOGIN_SHOW_PRICE') && !$app->cart->hasDownload());

            /* if (isset($_SESSION['accountType'])) {
              $data['accountType'] = $_SESSION['accountType'];
              } else {
              $data['accountType'] = 'register';
              } */
            //$model = new Customer;
            $data['forgotten'] = $this->createUrl('account/forgotpassword');
            $json['output'] = $this->renderPartial('checkout/login', array('data' => $data, 'model' => $model), true);
        }
        //echo '<pre>';print_r($json);echo '</pre>';exit;
        echo json_encode($json);
    }

    public function actionGuest() {
        $json = array();
        $app = Yii::app();
        $data['shipping_required'] = $app->cart->hasShipping();
        if ((int) Yii::app()->session['user_id']) {
			$json['redirect'] = $this->createUrl('checkout/checkout');
        }

        if ((!$app->cart->hasProducts()) || (!$app->cart->hasStock() && !$app->config->getData('CONFIG_STORE_ALLOW_CHECKOUT'))) {
            $json['redirect'] = $this->createUrl('checkout/carts');
        }

        if (!$app->config->getData('CONFIG_STORE_ALLOW_GUEST_CHECKOUT') || $app->cart->hasDownload()) {
            $json['redirect'] = $this->createUrl('checkout/checkout');
        }

        if ($_SERVER['REQUEST_METHOD'] == 'POST') {
            unset($_SESSION['billing']);
            unset($_SESSION['shipping']);
            if (!$json) {
                if ((strlen(utf8_decode($_POST['billing']['firstname'])) < 1) || (strlen(utf8_decode($_POST['billing']['firstname'])) > 32)) {
                    $json['error']['billing']['firstname'] = Yii::t('checkout', 'error_firstname');
                }

                if ((strlen(utf8_decode($_POST['billing']['lastname'])) < 1) || (strlen(utf8_decode($_POST['billing']['lastname'])) > 32)) {
                    $json['error']['billing']['lastname'] = Yii::t('checkout', 'error_lastname');
                }

                if ((strlen(utf8_decode($_POST['billing']['email'])) > 96) || !preg_match('/^[^\@]+@.*\.[a-z]{2,6}$/i', $_POST['billing']['email'])) {
                    $json['error']['billing']['email'] = Yii::t('checkout', 'error_email');
                }

                if ((strlen(utf8_decode($_POST['billing']['telephone'])) < 3) || (strlen(utf8_decode($_POST['billing']['telephone'])) > 32)) {

                    $json['error']['billing']['telephone'] = Yii::t('checkout', 'error_telephone');
                }

                if ((strlen(utf8_decode($_POST['billing']['address_1'])) < 3) || (strlen(utf8_decode($_POST['billing']['address_1'])) > 128)) {
                    $json['error']['billing']['address_1'] = Yii::t('checkout', 'error_address_1');
                }

                if ((strlen(utf8_decode($_POST['billing']['city'])) < 2) || (strlen(utf8_decode($_POST['billing']['city'])) > 128)) {
                    $json['error']['billing']['city'] = Yii::t('checkout', 'error_city');
                }

                if ((strlen(utf8_decode($_POST['billing']['postcode'])) < 2) || (strlen(utf8_decode($_POST['billing']['postcode'])) > 10)) {
                    $json['error']['billing']['postcode'] = Yii::t('checkout', 'error_postcode');
                }

                if ($_POST['billing']['id_country'] == '') {
                    $json['error']['billing']['id_country'] = Yii::t('checkout', 'error_country');
                }

                if ($_POST['billing']['id_state'] == '') {
                    $json['error']['billing']['id_state'] = Yii::t('checkout', 'error_state');
                }
            }

            if (!$json) {
                $_SESSION['billing']['firstname'] = $_POST['billing']['firstname'];
                $_SESSION['billing']['lastname'] = $_POST['billing']['lastname'];
                $_SESSION['billing']['email'] = $_POST['billing']['email'];
                $_SESSION['billing']['telephone'] = $_POST['billing']['telephone'];
                $_SESSION['billing']['company'] = $_POST['billing']['company'];
                $_SESSION['billing']['address_1'] = $_POST['billing']['address_1'];
                $_SESSION['billing']['address_2'] = $_POST['billing']['address_2'];
                $_SESSION['billing']['postcode'] = $_POST['billing']['postcode'];
                $_SESSION['billing']['city'] = $_POST['billing']['city'];
                $_SESSION['billing']['id_country'] = $_POST['billing']['id_country'];
                $_SESSION['billing']['id_state'] = $_POST['billing']['id_state'];


                $country_info = Library::getCountry($_POST['billing']['id_country']);
                if ($country_info) {
                    $_SESSION['billing']['country'] = $country_info['name'];
                    $_SESSION['billing']['iso_code_2'] = $country_info['iso_code_2'];
                    $_SESSION['billing']['iso_code_3'] = $country_info['iso_code_3'];
                    $_SESSION['billing']['address_format'] = $country_info['address_format'];
                    $_SESSION['billing']['call_prefix'] = $country_info['call_prefix'];
                }

                $state_info = Library::getState($_POST['billing']['id_state']);

                if ($state_info) {
                    $_SESSION['billing']['state'] = $state_info['name'];
                    $_SESSION['billing']['state_code'] = $state_info['code'];
                }

                unset($_SESSION['payment_methods']);
                unset($_SESSION['payment_method']);
            }

            //start guest shipping
            if (!$json && $data['shipping_required']) {
                if ((strlen(utf8_decode($_POST['shipping']['firstname'])) < 1) || (strlen(utf8_decode($_POST['shipping']['firstname'])) > 32)) {
                    $json['error']['shipping']['firstname'] = Yii::t('checkout', 'error_firstname');
                }

                if ((strlen(utf8_decode($_POST['shipping']['lastname'])) < 1) || (strlen(utf8_decode($_POST['shipping']['lastname'])) > 32)) {
                    $json['error']['shipping']['lastname'] = Yii::t('checkout', 'error_lastname');
                }

protected/views/checkout/checkout.php
<?php //echo $data['shipping_required'].'<pre>';print_r($data);echo '</pre>';?>
<div class="Categories-inner-pages"> 
<div class="col-md-8">
    <div class="check_out_page">
        <div class="tab-main-div">
            <div class="tab-main col-md-4 color-div " id="step1"><a href="#" onclick="fnStep(1);" ><?php echo 'Checkout Options';//Yii::t('checkout', 'text_checkout_options'); ?></a></div>
            <div class="tab-main col-md-4 "  id="step2" ><a href="#"  onclick="fnStep(2);" ><?php echo 'Billing & Shipping Details';//Yii::t('checkout', 'text_billing_shipping'); ?></a></div>
            <div class="tab-main col-md-4 "  id="step3" ><a href="#"  onclick="fnStep(3);" ><?php echo 'Shipping & Payment Method';//Yii::t('checkout', 'text_shipping_payment'); ?></a></div>
           
            <div class="clearfix" ></div>
        </div>
		<div class="notification-msg-div" id="notification"></div>
        <div class="checkout_options_div">
            <!--Content Loads Here-->
            <div class="clearfix" ></div>
        </div>
        <div class="clearfix" ></div>
    </div>
        </div>
        
            <div class="col-md-4 checkout-right-div ">
            <div class="tab-main confirm-right-div" ><a > Confirm order </a></div>
			<div id="confirm_order_div">
        <?php $this->renderPartial('checkout/checkoutorder', array("data" => $data)); ?>
   			 </div></div>
        
    <div class="clearfix" ></div>
</div>

<script type="text/javascript"><!--

function fnStep(val)
{
	if(val=='1')
	{
		$(document).ready(function() {
			$.ajax({
				url: '<?php if($data[logged]) { echo $this->createUrl("checkout/customer"); } else { echo $this->createUrl("checkout/login"); }?>',
				dataType: 'json',
				beforeSend: function() {
					$('#step1 a').after('<span class="wait">&nbsp;<img src="<?php echo Yii::app()->params[config][site_url];?>images/loading.gif" alt="" /></span>');
				},
				success: function(json) {
					if (json['redirect']) {
						location = json['redirect'];
					}

					if (json['output']) {
					$('.wait').remove();
						$('.checkout_options_div').html(json['output']);
						$("#step1").addClass("color-div");
						<?php if($data[logged]) {?>
						$("#step2").addClass("color-div");
						<?php } else {?>
						$("#step2").removeClass("color-div");
						<?php } ?>
						$("#step3").removeClass("color-div");
					}
				}
			});
		});
	}else if(val =='2')
	{
 	$(document).ready(function() {
	$.ajax({
		url: '<?php if(isset(Yii::app()->session['user_id'])){ echo $this->createUrl("checkout/customer"); }else{ echo $this->createUrl("checkout/guest"); }?>',
		dataType: 'json',
		beforeSend: function() {
			$('#step2  a').after('<span class="wait">&nbsp;<img src="<?php echo Yii::app()->params[config][site_url];?>images/loading.gif" alt="" /></span>');
		},
		success: function(json) {
			if (json['redirect']) {
				location = json['redirect'];
			}

			if (json['output']) {
				$('.wait').remove();
				$('.checkout_options_div').html(json['output']);
				$("#step1").addClass("color-div");
				$("#step2").addClass("color-div");
				$("#step3").removeClass("color-div");
				if ($('#guest_shipping_form').length == 0 || $('#guest_shipping_form').length < 0) {
				  $("#guest_billing_form").removeClass("col-md-6").addClass("col-md-12");
				}
				
			}
		}
	});
});

 
	}else if(val=='3')
	{
	$(document).ready(function() {
	$.ajax({
		url: '<?php echo $this->createUrl("checkout/ordermethod"); ?>',
		dataType: 'json',
		beforeSend: function() {
			$('#step3  a').after('<span class="wait">&nbsp;<img src="<?php echo Yii::app()->params[config][site_url];?>images/loading.gif" alt="" /></span>');
		},
		success: function(json) {
			if (json['redirect']) {
				location = json['redirect'];
			}

			if (json['output']) {
			$('.wait').remove();
			$('.checkout_options_div').html(json['output']);
			$("#step1").addClass("color-div");
			$("#step2").addClass("color-div");
			$("#step3").addClass("color-div");
			if ($('#shipping-left-div').length == 0 || $('#shipping-left-div').length < 0) {
				$("#shipping-right-div").removeClass("col-md-6").addClass("col-md-12");
			}		
		}
		}
	});
});


	}
}

<?php if (!$data['logged']) { ?>
$(document).ready(function() {
//alert("hell");
	$.ajax({
		url: '<?php echo $this->createUrl('checkout/login');?>',
		dataType: 'json',
		success: function(json) {
			if (json['redirect']) {
				location = json['redirect'];
			}

			if (json['output']) {
                            $('.checkout_options_div').html(json['output']);
			}
		}
	});
});
<?php } else { ?>
$(document).ready(function() {
	$.ajax({
		url: '<?php echo $this->createUrl("checkout/customer");?>',
		dataType: 'json',
		success: function(json) {
			if (json['redirect']) {
				location = json['redirect'];
			}

			if (json['output']) {
				$('.checkout_options_div').html(json['output']);
				$("#step2").addClass("color-div");
			}
		}
	});
});
<?php } ?>

$('body').on('click','#button_guest', function() {
	$.ajax({
		url: '<?echo $this->createUrl("checkout/guest");?>',
		dataType: 'json',
		beforeSend: function() {
	/*		
        //$('#button-account').attr('disabled', true);

			$('#button-account').after('<span class="wait">&nbsp;<img src="/includes/images/loading.gif" alt="" /></span>');*/
		},
		complete: function() {
			/*$('#button-account').attr('disabled', false);
			$('.wait').remove();*/
		},
		success: function(json) {
			//$('.warning').remove();

			if (json['redirect']) {
				location = json['redirect'];
			}

			if (json['output']) {
				$('.checkout_options_div').html(json['output']);
				$("#step2").addClass("color-div");
				if ($('#guest_shipping_form').length == 0 || $('#guest_shipping_form').length < 0) {
				  $("#guest_billing_form").removeClass("col-md-6").addClass("col-md-12");
				}
			}
		}
	});
});

// Guest
$('body').on('click','#guest_form_submit', function() {
	$.ajax({
		url: '<?php echo $this->createUrl("checkout/guest");?>',
		type: 'post',
		<?php if($data['shipping_required']){?>
		data: $('#guest_billing_form input[type=\'text\'],  #guest_billing_form select , #guest_shipping_form input[type=\'text\'],  #guest_shipping_form select'),
		<?php }else{?>
		data: $('#guest_billing_form input[type=\'text\'],  #guest_billing_form select'),
		<?php }?>
		
		dataType: 'json',
		beforeSend: function() {
			/*$('#button-guest').attr('disabled', true);
			$('#button-guest').after('<span class="wait">&nbsp;<img src="/includes/images/loading.gif" alt="" /></span>');*/
		},
		complete: function() {
			/*$('#button-guest').attr('disabled', false);
			$('.wait').remove();*/
		},
		success: function(json) {
			$('.errorMessage').remove();
                        //return;
			if (json['redirect']) {
				//location = json['redirect'];
			}

			if (json['error']) {
                            for (var key in json['error']['billing']) 
                            {
                                $('#billing_'+key).after('<div class="errorMessage">' + json['error']['billing'][key] + '</div>');
                            }
                            
                            for (var key in json['error']['shipping']) 
                            {
                                $('#shipping_'+key).after('<div class="errorMessage">' + json['error']['shipping'][key] + '</div>');
                            }
                            
			} else {
                                    $.ajax({

					url: '<?php echo $this->createUrl("checkout/ordermethod");?>',
					dataType: 'json',
					success: function(json) {
						/*if (json['redirect']) {
							location = json['redirect'];
						}*/

						if (json['output']) {
						$('.checkout_options_div').html(json['output']);
						$("#step3").addClass("color-div");
						if ($('#shipping-left-div').length == 0 || $('#shipping-left-div').length < 0) {
							$("#shipping-right-div").removeClass("col-md-6").addClass("col-md-12");
						}	
						}
						//$('#confirm_order_div').html('amazing');
						//alert("at last")
					}
				});
                               
                               }
		}
	});
});

// Login
$('body').on('click','#button-login', function() {
	//alert('in login');return;
	$.ajax({
		url: '<?echo $this->createUrl("checkout/login");?>',
		type: 'post',
		data: $('.mailid-div :input'),
		dataType: 'json',
		beforeSend: function() {
			//$('#button-login').attr('disabled', true);

			$('#button-login').after('<span class="wait">&nbsp;<img src="<?php echo Yii::app()->params[config][site_url];?>images/loading.gif"  /></span>');

		},
		complete: function() {
			$('#button-login').attr('disabled', false);
			//$('.wait').remove();
		},
		success: function(json) {
			$('.wait').remove();
			$('.alert-danger').remove();

			if (json['redirect']) {
				location = json['redirect'];
			}

			if (json['error']) {
				//$('.checkout_options_div').prepend('<div class="warning">' + json['error']['warning'] + '</div>');
				$('#notification').prepend('<div class="alert in fade alert-danger">' + json['error']['warning'] + '<a data-dismiss="alert" class="close" style="cursor:pointer">×</a></div>');

			} else {
				$.ajax({
					url: '<?echo $this->createUrl("checkout/customer");?>',
					dataType: 'json',
					success: function(json) {
						if (json['redirect']) {
							location = json['redirect'];
						}

						if (json['output']) {
							$('.checkout_options_div').html(json['output']);
							$("#step2").addClass("color-div");
							if ($('#guest_shipping_form').length == 0 || $('#guest_shipping_form').length < 0) {
				  				$("#guest_billing_form").removeClass("col-md-6").addClass("col-md-12");
							}
						 }
					}
				});
			}
		}
	});
});


// Address
$('body').on('click','#button_customer', function() {
	$.ajax({
		url: '<?php echo $this->createUrl("checkout/customer");?>',
		type: 'post',
		data: $('#customer_address_form input[type=\'text\'],  #customer_address_form select'),
		dataType: 'json',
		beforeSend: function() {
			/*$('#button-guest').attr('disabled', true);
			$('#button-guest').after('<span class="wait">&nbsp;<img src="/includes/images/loading.gif" alt="" /></span>');*/
		},
		complete: function() {
			/*$('#button-guest').attr('disabled', false);
			$('.wait').remove();*/
		},
		success: function(json) {
			$('.errorMessage').remove();
                        //return;
			if (json['redirect']) {
				//location = json['redirect'];
			}

			if (json['error']) {
				for (var key in json['error']['address']) 
				{
					$('#address_'+key).after('<div class="errorMessage">' + json['error']['address'][key] + '</div>');
				}
            }

			if (json['output']) {
			$('.checkout_options_div').html(json['output']);
			}
		}
	});
});

$('body').on('click','#button_select_address', function() {
	$.ajax({
		url: '<?php echo $this->createUrl("checkout/customeraddress");?>',
		type: 'post',
		//data: $('#customer_select_form input[type=\'radio\']'),
		data: $('#customer_select_form input[type=\'radio\']:checked'),
		dataType: 'json',
		beforeSend: function() {
			/*$('#button-guest').attr('disabled', true);
			$('#button-guest').after('<span class="wait">&nbsp;<img src="/includes/images/loading.gif" alt="" /></span>');*/
		},
		complete: function() {
			/*$('#button-guest').attr('disabled', false);
			$('.wait').remove();*/
		},
		success: function(json) {
		//$('.warning').remove();
		$('.alert-danger').remove();
			if (json['error']) {
				//$('.checkout_options_div').prepend('<div class="warning">' + json['error'] + '</div>');	
				$('#notification').prepend('<div class="alert in fade alert-danger">' + json['error'] + '<a data-dismiss="alert" class="close" style="cursor:pointer">×</a></div>');
            } else {
				$.ajax({
					url: '<?echo $this->createUrl("checkout/ordermethod");?>',
					dataType: 'json',
					success: function(json) {
						if (json['redirect']) {
							location = json['redirect'];
						}

						if (json['output']) {
							$('.checkout_options_div').html(json['output']);
							$("#step3").addClass("color-div");
						 }
						//$('#confirm_order_div').html('amazing');
						//alert("at last")
					}
				});
			}
		}
	});
});

$('body').on('click','#shipping_method , #payment_method , #agree', function() {
	$.ajax({
		url: '<?echo $this->createUrl("checkout/ordermethod");?>',
		type: 'post',
		//data: $('#frmcheckoutmethod :input'),
		data: $('#frmcheckoutmethod input[type=\'radio\']:checked,#frmcheckoutmethod input[type=\'checkbox\']:checked'),
		dataType: 'json',
		beforeSend: function() {
	/*		
        //$('#button-account').attr('disabled', true);

			$('#button-account').after('<span class="wait">&nbsp;<img src="/includes/images/loading.gif" alt="" /></span>');*/
		},
		complete: function() {
			/*$('#button-account').attr('disabled', false);
			$('.wait').remove();*/
		},
		success: function(json) {
			//$('.warning').remove();
			$('.alert-danger').remove();

			if (json['redirect']) {
				location = json['redirect'];
			}

			if (json['error']) 
			{
				for (var key in json['error']) 
				{
					//$('.checkout_options_div').prepend('<div class="warning">' + json['error'][key] + '</div>');
					$('#notification').prepend('<div class="alert in fade alert-danger">' + json['error'][key] + '<a data-dismiss="alert" class="close" style="cursor:pointer">×</a></div>');
				}
			}

			if (json['checkoutOrder']) {
				//alert(json['checkoutOrder'])
				//$('.checkout_options_div').html(json['output']);
				$('#confirm_order_div').html(json['checkoutOrder']);
				$("#step2").addClass("color-div");
			}
			//alert(json['confirmButton'])
			$('#confirmButton').html(json['confirmButton']);
			
			
		}
	});
});
//--></script>

protected/views/checkout/checkout2.php
   <div class="Categories-inner-pages"> 
   
   <div class="check_out_page">
   
   <div class="tab-main-div">
   <div class="tab-main col-md-3 actave "><a href="index.php?r=site/page&view=Chackout"  >Checkout options </a></div>
   <div class="tab-main col-md-3 actave "><a href="index.php?r=site/page&view=Chackout1" > Billing & Shipping Info </a></div>
   <div class="tab-main col-md-3 color-div "><a href="index.php?r=site/page&view=Chackout2" > Shipping  & Payment </a></div>
   <div class="tab-main col-md-3 "><a href="index.php?r=site/page&view=Chackout3" > Confirm order </a></div>
   <div class="clearfix" ></div>
   </div>
   
   <div class="checkout_options_div">
   
   <div class="row col-md-12 checkout_main_div">
   
    <div class="col-md-8 border-line-div">
    <div class="col-md-6">
    <h4>Shipping Method</h4>
    
    <div class="">
    <p>Please select the preferred service to use on this order.</p>
 	<h6>Choose Shipping Method</h6>
    
  <h5>  Shipping Method</h5>

<table class="table">
<tr>
<td>Express</td>
<td> Rs.5.00</td>
<td><input type="radio" class=""  /></td>
</tr>


<tr>
<td>Express</td>
<td> Rs.5.00</td>
<td><input type="radio" class=""  /></td>
</tr>

</table>

    
    </div>
    
    </div>
    
     <div class="col-md-6">
    <h4>Payment Method</h4>
    
        <div class="">
    <p>Please select the preferred service to use on this order.</p>
 	
    <table class="table">
<tr>
<td>  Cash On Delivery</td>

<td><input type="radio" class=""  /></td>
</tr>


<tr>
<td>Credit Card  |  Debit Card  |  Internet Banking</td>
<td><input type="radio" class=""  /></td>
</tr>



</table>
  <p>I have read and agree to the Privacy Policy  <input type="radio" class=""  /></p>
    
  <p> <?php $this->widget('bootstrap.widgets.TbButton', array('type' => 'primary','size' => 'inverse', 'label' => 'Confirm order', 'htmlOptions'=>array('class'=>'addtocart', 'url' => $this->createAbsoluteUrl('account/orderdetails',array('id'=>$data->id_order))), )); ?></p>
    
    </div>
    
    </div>
    
    </div>

<div class="col-md-4">

<table width="100%" border="0" cellspacing="0" class="table table-online-div" cellpadding="0">

 <tr class="prodct-div-main" >
  <th scope="col"><strong>Product(s)</strong></th>
  <th scope="col"><strong>Qty</strong></th>
  <th scope="col" class="table-online-midel"><strong>Price</strong></th>
 </tr>
 
 <tr>
  <td style="text-align:center">
  <img src="/themelite/themes/sproanzoOS/img/crt-1.jpg" height="50" width="36"  alt="" /><br />
  Nokia Lumia 520 Black</td>
  <td><strong>1</strong></td>
  <td class="table-online-right"><strong>Rs 7999</strong></td>
 </tr>
 
 <tr>
  <td style="text-align:center">
  <img src="/themelite/themes/sproanzoOS/img/crt-1.jpg" height="50" width="36"  alt="" /><br />
  Nokia Lumia 520 Black</td>
  <td><strong>1</strong></td>
  <td class="table-online-right"><strong>Rs 7999</strong></td>
 </tr>
 
  
 <tr class="table-online-main">
  <td colspan="2">Subtotal     </td>
  <td><strong> Rs.15998</strong></td>
 </tr>
 
  <tr class="table-online-main">
  <td colspan="2">Shipping Charges		     </td>
  <td><strong>Free</strong></td>
 </tr>
 
  <tr class="table-online-main">
  <td colspan="2">Vat Charges  </td>
  <td><strong> Free </strong></td>
 </tr>
 
  <tr class="total-div-main table-online-main">
  <td colspan="2">TOTAL </td>
  <td><strong> Rs   15998 </strong></td>
 </tr>


</table>

</div>


   
   <div class="clearfix" ></div>
   </div>
   
   <div class="clearfix" ></div>
   </div>
   <div class="clearfix" ></div>
   </div>
   <div class="clearfix"></div>
   </div>
   

protected/views/checkout/success.php
<div class="col-md-12">
	<div class="heading-box">
		<h2><?php echo $data['title'];?></h2>
	</div>
	<div ><?php echo $data['text_message'];?></div>
</div>